### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by abconnor** [andrewheiss/gif_timer#1]
I wanted to create a 60 minutes Countdown and so I set the variable "seconds" to "60 * 60". Then this error appears:

Traceback (most recent call last):
  File "timer_gif.py", line 47, in <module>
    gif.sequence.append(img)
  File "/home/andreas/.local/lib/python2.7/site-packages/wand/sequence.py", line 207, in append
    library.MagickAddImage(wand, image.sequence[0].wand)
  File "/home/andreas/.local/lib/python2.7/site-packages/wand/sequence.py", line 112, in __getitem__
    index = self.validate_position(index)
  File "/home/andreas/.local/lib/python2.7/site-packages/wand/sequence.py", line 82, in validate_position
    'out of index: {0} (total: {1})'.format(index, length)
IndexError: out of index: 0 (total: 0)

Any suggestions?

**Comment by andrewheiss** [comment]
You have to use Python 3, not 2
